### ISSUE TITLE
Bot code is in wrong order

### ISSUE THREAD

**Issue by NootNootEliot** [NootNootEliot/seng#21]
`bot.processes` should be moved underneath the instantiation of `bot`.

**Comment by zliel** [comment]
Hello @NootNootEliot, would it be okay if I did this?

**Comment by NootNootEliot** [comment]
Hey @zliel! Sure thing, take a look at `bot.py` :)

**Comment by zliel** [comment]
Just finished up, if anything is wrong with my PR please let me know! Thank you!

**Comment by NootNootEliot** [comment]
Nice job @zliel! Thanks very much :)
